name: Update docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Extract version from tag
        id: extract_tag
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

      - name: Replace %version% in index.html
        run: |
          tag=${{ steps.extract_tag.outputs.VERSION }}
          sed -i "s#%version%#${tag}#g" index.html

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /
          server-dir: /
          exclude: |
            * # исключить все файлы
            !index.html # но включить index.html
            !index.es.js # и index.es.js